apiVersion: v1
kind: Service
metadata:
  name: i27-helpdesk-ui
  namespace: i27-helpdesk-dev

spec:
  selector:
    app: i27-helpdesk-ui

  ports:
    - name: http
      port: 80
      targetPort: 3000

  type: ClusterIP
